apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-disk
  namespace: vms-git
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: git-import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: px-csi-replicated
  resources:
    requests:
      storage: 30Gi
