apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pleasant-piranha-disk
  namespace: vms
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: pleasant-import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  resources:
    requests:
      storage: 30Gi
